#!/bin/bash -eu

echo $DIR_KUBECONFIG
echo $CLUSTER_NAME
echo $DIR_SSL


CA_PATH=$DIR_SSL/${CLUSTER_NAME}/ca.pem
ADMIN_CERT_PATH=$DIR_SSL/${CLUSTER_NAME}/admin.pem
ADMIN_KEY_PATH=$DIR_SSL/${CLUSTER_NAME}/admin-key.pem
KUBE_API_PUBLIC_FQDN=`terraform output -state=build/${CLUSTER_NAME}/terraform.tfstate kube-api-public-fqdn`


mkdir -p $DIR_KUBECONFIG


cat << EOF > ${DIR_KUBECONFIG}/kubeconfig
kubectl config set-cluster cluster-${CLUSTER_NAME} \
  --embed-certs=true \
  --server=https://${KUBE_API_PUBLIC_FQDN}:6443  \
  --certificate-authority=${CA_PATH}

kubectl config set-credentials admin-${CLUSTER_NAME} \
  --embed-certs=true \
  --certificate-authority=${CA_PATH} \
  --client-key=${ADMIN_KEY_PATH} \
  --client-certificate=${ADMIN_CERT_PATH}

kubectl config set-context ${CLUSTER_NAME} \
  --cluster=cluster-${CLUSTER_NAME} \
  --user=admin-${CLUSTER_NAME}

kubectl config use-context ${CLUSTER_NAME}
EOF

kubectl config set-cluster cluster-${CLUSTER_NAME} \
  --embed-certs=true \
  --server=https://${KUBE_API_PUBLIC_FQDN}:6443 \
  --certificate-authority=${CA_PATH}

kubectl config set-credentials admin-${CLUSTER_NAME} \
  --embed-certs=true \
  --certificate-authority=${CA_PATH} \
  --client-key=${ADMIN_KEY_PATH} \
  --client-certificate=${ADMIN_CERT_PATH}

kubectl config set-context ${CLUSTER_NAME} \
  --cluster=cluster-${CLUSTER_NAME} \
  --user=admin-${CLUSTER_NAME}

kubectl config use-context ${CLUSTER_NAME}
