#!/bin/bash

BOOTSTRAP_TOKEN=$(grep bootstrap_token terraform.tfvars | cut -f3 -d " "|tr -d '"')
IFS=. read TOKEN_ID TOKEN_CONTENT <<< $BOOTSTRAP_TOKEN
TOKENID_BASE64=$(base64 <<< $TOKEN_ID)
TOKEN_CONTENT_BASE64=$(base64 <<< $TOKEN_CONTENT)

echo $BOOTSTRAP_TOKEN
echo $TOKEN_ID
echo $TOKEN_CONTENT


cat <<EOF | echo
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-${TOKEN_ID}
  namespace: kube-system
data:
  auth-extra-groups: c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=
  description: VGhlIGRlZmF1bHQgYm9vdHN0cmFwIHRva2VuIGdlbmVyYXRlZCBieSAna3ViZWFkbSBpbml0Jy4=
  token-id: ${TOKENID_BASE64}
  token-secret: ${TOKEN_CONTENT_BASE64}
  usage-bootstrap-authentication: dHJ1ZQ==
  usage-bootstrap-signing: dHJ1ZQ==
type: bootstrap.kubernetes.io/token
EOF
