#!/bin/bash

BOOTSTRAP_TOKEN=$(grep bootstrap_token terraform.tfvars | cut -f3 -d " "|tr -d '"')
TOKEN_ID=$(cut -f1 -d '.' <<< $BOOTSTRAP_TOKEN)
TOKEN_ID_BASE64=$(cut -f1 -d '.' <<< $BOOTSTRAP_TOKEN | base64 -w0)
TOKEN_CONTENT_BASE64=$(cut -f2 -d '.' <<< $BOOTSTRAP_TOKEN | base64 -w0)

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-${TOKEN_ID}
  namespace: kube-system
data:
  auth-extra-groups: c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=
  description: VGhlIGRlZmF1bHQgYm9vdHN0cmFwIHRva2VuIGdlbmVyYXRlZCBieSAna3ViZWFkbSBpbml0Jy4=
  token-id: ${TOKEN_ID_BASE64}
  token-secret: ${TOKEN_CONTENT_BASE64}
  usage-bootstrap-authentication: dHJ1ZQ==
  usage-bootstrap-signing: dHJ1ZQ==
type: bootstrap.kubernetes.io/token
EOF
