#!/bin/bash -e

CDIR=$(dirname "${BASH_SOURCE}")

SP_PATH=${SP_PATH:-~/packer-sp.json}
SUBSCRIPTION_ID=${SUBSCRIPTION_ID:-`az account show --query="id" | tr -d '"'`}

echo "Subscription ID: ${SUBSCRIPTION_ID}"
echo "Service Principal Path: ${SP_PATH}"

if [ -a "${SP_PATH}" ]; then
	client_id=`cat ${SP_PATH} | jq -r .appId`
	client_secret=`cat ${SP_PATH} | jq -r .password`
	tenant_id=`cat ${SP_PATH} | jq -r .tenant`
else
	echo "Service principal file not found! Generating one @ ${SP_PATH}"
	az ad sp create-for-rbac -n acstack-packer -o json > ${SP_PATH}
	client_id=`cat ${SP_PATH} | jq -r .appId`
	client_secret=`cat ${SP_PATH} | jq -r .password`
	tenant_id=`cat ${SP_PATH} | jq -r .tenant`
fi

if [ -z "${client_id}" ]; then
	echo "client_id was not set! Something happened when generating the service principal or when trying to read the sp file!"
	exit 1
fi

if [ -z "${client_secret}" ]; then
	echo "client_secret was not set! Something happened when generating the service principal or when trying to read the sp file!"
	exit 1
fi

if [ -z "${tenant_id}" ]; then
	echo "tenant_id was not set! Something happened when generating the service principal or when trying to read the sp file!"
	exit 1
fi

cat <<EOF > settings.json
{
  "subscription_id":  "${SUBSCRIPTION_ID}",
  "client_id": "${client_id}",
  "client_secret": "${client_secret}",
  "tenant_id":      "${tenant_id}",
  "resource_group_name": "${AZURE_RESOURCE_GROUP_NAME}",
  "location": "${AZURE_LOCATION}",
  "vm_size": "${AZURE_VM_SIZE}"
}
EOF

cat settings.json
